version: "3.7"

services:
  db_test:
    image: postgres:15.1-alpine
    container_name: db_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .test.env

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    container_name: tests
    env_file:
      - .test.env
    depends_on:
      db_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy

  redis_test:
      image: redis:7.0-alpine
      container_name: redis_test
      env_file:
        - .test.env
      healthcheck:
        test: ["CMD-SHELL", "redis-cli ping"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      ports:
        - 6379:6379
      restart: always
      

