version: "3.7"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_test
    env_file:
      - .env

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    container_name: tests
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

      