version: "3.7"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db_app
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d homework"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 
      