version: "3.7"

services:
  db_test:
    image: postgres:15.1-alpine
    container_name: db_test
    env_file:
      - .test.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5433 -U postgres -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5433"
    command: -p 5433
    restart: always

  redis_test:
    image: redis:7.0-alpine
    container_name: redis_test
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "6380:6380"
    restart: always

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    container_name: tests
    env_file:
      - .test.env
    depends_on:
      db_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy
