"""change menu name to title

Revision ID: dedec643cd8c
Revises: 800e6c5a4d54
Create Date: 2023-07-25 17:05:57.753795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedec643cd8c'
down_revision = '10a9741dd86b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint('dish_name_key', 'dish', type_='unique')
    op.create_unique_constraint(None, 'dish', ['title'])
    op.drop_column('dish', 'name')
    op.add_column('menu', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint('menu_name_key', 'menu', type_='unique')
    op.create_unique_constraint(None, 'menu', ['title'])
    op.drop_column('menu', 'name')
    op.add_column('submenu', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint('submenu_name_key', 'submenu', type_='unique')
    op.create_unique_constraint(None, 'submenu', ['title'])
    op.drop_column('submenu', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'submenu', type_='unique')
    op.create_unique_constraint('submenu_name_key', 'submenu', ['name'])
    op.drop_column('submenu', 'title')
    op.add_column('menu', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu', type_='unique')
    op.create_unique_constraint('menu_name_key', 'menu', ['name'])
    op.drop_column('menu', 'title')
    op.add_column('dish', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dish', type_='unique')
    op.create_unique_constraint('dish_name_key', 'dish', ['name'])
    op.drop_column('dish', 'title')
    # ### end Alembic commands ###
